verison: "1"

services:
  app:
    container_name: 'aplicação-node'
    build: .
    command: npm start
    ports: 
      - "3000:3000"
    volumes:
      - .:/usr/app
    depends_on:
      - db
    links:
     - db
  db:
    container_name: 'database-mysql'
    image: mysql:6
    restart: always
    volumes:
      - dbdata-volume:/data/db
    ports:
      - '3308:3306'
    environment:
      - MYSQL_DATABASE=usuarios
      -  MYSQL_USER=root
      - MYSQL_PASSWORD= ''
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo
volumes:
  dbdata-volume: